export const HOME = {
  emergentLink: "emergent-link",
  heroTitle: "hero-title",
  langHinglish: "lang-hinglish",
  langHindi: "lang-hindi",
  langEnglish: "lang-english",
  modeCard: (mode) => `mode-card-${mode}`,
  quickLafda: "quick-lafda",
  quickCooked: "quick-cooked",
  quickAura: "quick-aura",
  quickLife: "quick-life",
  quickCourt: "quick-court",
  quickLockin: "quick-lockin",
  quickProfile: "quick-profile",
  ctaTalk: "cta-talk",
};

export const CHAT = {
  root: "chat-root",
  header: "chat-header",
  backBtn: "chat-back",
  modeTitle: "chat-mode-title",
  input: "chat-input",
  sendBtn: "chat-send",
  roastHarder: "chat-roast-harder",
  clearBtn: "chat-clear",
  statsBtn: "chat-stats",
  intensitySlider: "chat-intensity",
  characterPicker: "chat-character",
  characterOption: (id) => `chat-character-${id}`,
  message: (id) => `msg-${id}`,
  messagesList: "chat-messages",
};

export const LOCKIN = {
  root: "lockin-root",
  taskInput: "lockin-task",
  minutesInput: "lockin-minutes",
  planBtn: "lockin-plan",
  startBtn: "lockin-start",
  pauseBtn: "lockin-pause",
  stopBtn: "lockin-stop",
  timer: "lockin-timer",
  stepList: "lockin-steps",
  completeBtn: "lockin-complete",
};

export const PROFILE = {
  dialog: "profile-dialog",
  canvas: "profile-canvas",
  download: "profile-download",
};

export const SPECIAL = {
  lafdaDialog: "lafda-dialog",
  lafdaHeadline: "lafda-headline",
  lafdaRegen: "lafda-regen",
  cookedDialog: "cooked-dialog",
  cookedInput: "cooked-input",
  cookedSubmit: "cooked-submit",
  cookedResult: "cooked-result",
  auraDialog: "aura-dialog",
  auraInput: "aura-input",
  auraSubmit: "aura-submit",
  auraResult: "aura-result",
  lifeDialog: "life-dialog",
  lifeInput: "life-input",
  lifeSubmit: "life-submit",
  lifeResult: "life-result",
  courtDialog: "court-dialog",
  courtInput: "court-input",
  courtSubmit: "court-submit",
  courtResult: "court-result",
  shareBtn: "share-btn",
};
